### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Lantoit** [LucaPatarca/homeassistant_aton#9]
Hi, the Aton Storage Unofficial has stopped working.

This error originated from a custom integration.

Logger: custom_components.aton_storage.sensor
Source: helpers/update_coordinator.py:354
integration: Aton Storage Unofficial (documentation)
First occurred: 13:11:19 (114 occurrences)
Last logged: 14:07:53

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/aton_storage/sensor.py:431
integration: Aton Storage Unofficial (documentation)
First occurred: 13:11:19 (1 occurrences)
Last logged: 13:11:19

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 453, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/aton_storage/sensor.py", line 431, in _handle_coordinator_update
    self._attr_native_value = round(self.coordinator.api.status.self_sufficiency, 2)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyaton.py", line 92, in self_sufficiency
    return 100 - ((self.bought_energy / self.consumed_energy) * 100)
                   ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: division by zero

Unexpected error fetching Aton Storage data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aton_storage/sensor.py", line 101, in _async_update_data
    return await self.hass.async_add_executor_job(self.api.fetch_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyaton.py", line 188, in fetch_data
    self.status.update(data)
  File "/usr/local/lib/python3.12/site-packages/pyaton.py", line 46, in update
    self.battery_status = float(json["soc"])
                                ~~~~^^^^^^^
TypeError: 'bool' object is not subscriptable

**Comment by Lantoit** [comment]
After few hours the integration is now working, Aton outage?
